# 下载最新的0.25°ECMWF公开预报数据

## 项目背景

目前，世界主要的全球数值模式有欧洲中期数值、美国全球模式、中国全球模式等。其中，欧洲中期数值天气预报中心（ECMWF）开发的欧洲中期数值，自1979年发布以来，逐步建立了在数值天气预报领域中的领先地位，受到了气象科研人员和相关行业的广泛关注。  

对寒潮、热浪、台风等大型天气，欧洲中期数值素来有“神算子”之称，世界各国的天气预报，欧洲中期数值产品都是重要的参考。  

从2022年1月25日起，ECMWF 在全球范围内的大量预测数据将公开提供。  

从2024年2月1日起，EMCWF 公开预报数据的分辨率从0.4°提升到0.25°！  

欧洲中期数值模式的数据开放，让公众更轻易的接触到气象产品，其中蕴藏着巨大的待挖掘价值。  

> 相关链接：https://openmeteo.substack.com/p/ecmwf-ifs-upgraded-to-025-resolution  



## ECMWF公开预报数据简介

### 下载地址




ECMWF公开预报数据下载地址：https://data.ecmwf.int/forecasts/  
![Image Name](https://cdn.kesci.com/upload/s98sxbufco.png)

### 可获取变量

除了高分辨率决定性预报（deterministic forecast），ECMWF同时也公开了海量集合预报（ensemble forecast）数据，不仅有上述的预报变量，还包含热带气旋路径、天气事件概率等预报产品。  

以高分辨率数据为例：  
+ 起报时间为00z和12z，预报步长为0 ~ 144h，分辨率为3h；150 ~ 240h，分辨率为6h。  
+ 起报时间为06z和18z，预报步长为0 ~ 90h，分辨率为3h。  
+ 气压层：1000, 925, 850, 700, 500, 300, 250, 200, 50 hPa  

$$  
\begin{array}{|c|c|c|c|}  
\hline \text { Short name } & \text { Long name } & \text { ID } & \text { Level } \\  
\hline 10 u & 10 \text { metre U wind component } & 165 & \text { Single } \\  
\hline 10 \mathrm{v} & 10 \text { metre V wind component } & 166 & \text { Single } \\  
\hline 2 \mathrm{t} & 2 \text { metre temperature } & 167 & \text { Single } \\  
\hline \text { msl } & \text { Mean sea level pressure } & 151 & \text { Single } \\  
\hline \text { mp2 } & \text { Mean zero-crossing wave period } & 140221 & \text { Single } \\  
\hline \text { mwd } & \text { Mean wave direction } & 140230 & \text { Single } \\  
\hline \text { mwp } & \text { Mean wave period } & 140232 & \text { Single } \\  
\hline \text { pp1d } & \text { Peak wave period } & 140231 & \text { Single } \\  
\hline \text { swh } & \text { Significant height of combined wind waves and swell } & 140229 & \text { Single } \\  
\hline \text { ro } & \text { Runoff } & 205 & \text { Single } \\  
\hline \text { tp } & \text { Total Precipitation } & 228 & \text { Single } \\  
\hline \mathrm{sp} & \text { Surface pressure } & 134 & \text { Single } \\  
\hline \text { st } & \text { Soil temperature } & 228139 & \text { Single } \\  
\hline \text { tcwv } & \text { Total column vertically-integrated water vapour } & 137 & \text { Single } \\  
\hline \text { d } & \text { Divergence } & 155 & \text { Pressure } \\  
\hline \text { gh } & \text { Geopotential height } & 156 & \text { Pressure } \\  
\hline \text { q } & \text { Specific humidity } & 133 & \text { Pressure } \\  
\hline \text { r } & \text { Relative humidity } & 157 & \text { Pressure } \\  
\hline \text { t } & \text { Temperature } & 130 & \text { Pressure } \\  
\hline \text { u } & \text { U component of wind } & 131 & \text { Pressure } \\  
\hline \text { v } & \text { V component of wind } & 132 & \text { Pressure } \\  
\hline \text { vo } & \text { Vorticity (relative) } & 138 & \text { Pressure } \\  
\hline  
\end{array}  
$$  


> 更多预报产品数据变量说明：https://www.ecmwf.int/en/forecasts/datasets/open-data

## 两个ECMWF预报数据下载模块

### Hebie-data

`herbie-data`模块PyPI地址：https://pypi.org/project/herbie-data/  
+ 优势：可以获取历史的ECMWF预报数据  
+ 不足：目前分辨率只有0.4°  

![Image Name](https://cdn.kesci.com/upload/s98typd8ug.png)  

> 参考项目：https://herbie.readthedocs.io/en/latest/user_guide/_model_notebooks/ecmwf.html

### ecmwf.opendata

`ecmwf.opendata`模块PyPI地址：https://pypi.org/project/ecmwf-opendata/  
+ 优势：可以获取0.25°和0.4°的ECMWF预报数据  
+ 不足：无法获取历史预报数据，只有近实时的预报数据  

本项目利用`ecmwf.opendata`模块获取0.25°的ECMWF公开预报数据  

> 特别感谢参考项目：[正则啊正则 | ECMWF数据获取与处理](https://www.heywhale.com/mw/project/6564353b861653ff00cc50ef)

## 导入模块

In [1]:
from ecmwf.opendata import Client
import numpy as np
import netCDF4 as nc
import time
import datetime
import requests
from glob import glob
from tqdm import tqdm
import os

## 查询最新的起报时间

In [2]:
client = Client(source="ecmwf")
# 通过latest方法可以获取当前EC数据发布的最近起报时
start_time = client.latest(type='fc')
start_time

datetime.datetime(2024, 2, 21, 18, 0)

## 下载ECMWF预报数据

In [3]:
client = Client(source='ecmwf')
client.retrieve(
        date='2024-02-21',        # 预报开始的日期
        time='18',                # 预报开始的时间（一天有4个时刻，分为00、06、12、18UTC）
        type='fc',                # 数据类型，这里fc代表forecast
        stream='oper',
        param=['2t', 'sp'],       # 变量类型，这里选择了2m温度和表面气压
        step=3,                   # 预测步长，如果当前起报时为2024年02月21号18点，那么通过该方法会返回21点的数据
        target='data.grib2')      # 文件存储名称

20240221060000-3h-scda-fc.grib2:   0%|          | 0.00/518k [00:00<?, ?B/s]

## 查看ECMWF预报数据

In [4]:
import pygrib as pg

filename = 'data.grib2'
grb = pg.open(filename)

In [5]:
g = grb[1]  # 索引从1开始（如果用多个变量，索引从1开始）
lat, lon = g.latlons()

In [6]:
# 打印纬度，此处的分辨率为0.4°
print(lat)

[[ 90.   90.   90.  ...  90.   90.   90. ]
 [ 89.6  89.6  89.6 ...  89.6  89.6  89.6]
 [ 89.2  89.2  89.2 ...  89.2  89.2  89.2]
 ...
 [-89.2 -89.2 -89.2 ... -89.2 -89.2 -89.2]
 [-89.6 -89.6 -89.6 ... -89.6 -89.6 -89.6]
 [-90.  -90.  -90.  ... -90.  -90.  -90. ]]


In [7]:
# 打印经度，此处的分辨率为0.4°
print(lon)

[[-180.  -179.6 -179.2 ...  178.8  179.2  179.6]
 [-180.  -179.6 -179.2 ...  178.8  179.2  179.6]
 [-180.  -179.6 -179.2 ...  178.8  179.2  179.6]
 ...
 [-180.  -179.6 -179.2 ...  178.8  179.2  179.6]
 [-180.  -179.6 -179.2 ...  178.8  179.2  179.6]
 [-180.  -179.6 -179.2 ...  178.8  179.2  179.6]]


In [8]:
# 打印数值
print(g.values)

[[101512.3828125 101512.3828125 101512.3828125 ... 101512.3828125
  101512.3828125 101512.3828125]
 [101576.3828125 101576.3828125 101576.3828125 ... 101576.3828125
  101576.3828125 101576.3828125]
 [101608.3828125 101608.3828125 101608.3828125 ... 101608.3828125
  101608.3828125 101608.3828125]
 ...
 [ 66552.3828125  66568.3828125  66584.3828125 ...  66520.3828125
   66536.3828125  66536.3828125]
 [ 67496.3828125  67512.3828125  67512.3828125 ...  67480.3828125
   67480.3828125  67496.3828125]
 [ 68584.3828125  68584.3828125  68584.3828125 ...  68584.3828125
   68584.3828125  68584.3828125]]


In [9]:
# 打印变量名称
print(g.name)

Surface pressure


In [10]:
# 打印变量单位
print(g.units)

Pa


In [11]:
# 打印变量高度，表面气压的高度为0
print(g.level)

0


## 获取未来不同预报步长下0.4°ECMWF地面和高空预报数据

### 0.4°ECMWF地面数据

In [12]:
client = Client(source='ecmwf')

for step in np.arange(0,12,3):
    # 通过.retrieve()方法获取想要的预报数据
    client.retrieve(
        date=start_time.strftime('%Y-%m-%d'),    #预报开始的日期
        time=start_time.strftime('%H'),          #预报开始的时间
        type='fc',                               #数据类型
        stream='oper',
        param=['2t', 'sp'],                      #变量类型，这里选择了2m温度和表面气压
        step=str(step),                          #预测步长，基于起报时间往后推
        target='ecmwf_2d_{}_fc_{}_0p4.grib2'.format(start_time.strftime('%Y%m%d%H'),str(step)), #文件存储名称
        )

20240221180000-0h-scda-fc.grib2:   0%|          | 0.00/520k [00:00<?, ?B/s]

20240221180000-3h-scda-fc.grib2:   0%|          | 0.00/519k [00:00<?, ?B/s]

20240221180000-6h-scda-fc.grib2:   0%|          | 0.00/518k [00:00<?, ?B/s]

20240221180000-9h-scda-fc.grib2:   0%|          | 0.00/518k [00:00<?, ?B/s]

### 0.4°ECMWF高空数据

In [13]:
client = Client(source='ecmwf')
for step in np.arange(0,12,3):
    #通过.retrieve()方法获取想要的预报数据
    client.retrieve(
        date=start_time.strftime('%Y-%m-%d'),   #预报开始的日期
        time=start_time.strftime('%H'),         #预报开始的时间
        type='fc',                              #数据类型
        stream='oper',
        param=['u', 'v'],                       #变量类型，这里选择了2m温度和表面气压
        levelist=['850','500','200'], 
        step=str(step),           #预测步长，如果当前起报时为2024年02月21号00点，那么通过该方法会返回15点的数据
        target='ecmwf_3d_{}_fc_{}_0p4.grib2'.format(start_time.strftime('%Y%m%d%H'),str(step)), #存储名称
        )

20240221180000-0h-scda-fc.grib2:   0%|          | 0.00/1.78M [00:00<?, ?B/s]

20240221180000-3h-scda-fc.grib2:   0%|          | 0.00/1.77M [00:00<?, ?B/s]

20240221180000-6h-scda-fc.grib2:   0%|          | 0.00/1.77M [00:00<?, ?B/s]

20240221180000-9h-scda-fc.grib2:   0%|          | 0.00/1.82M [00:00<?, ?B/s]

## 获取未来不同预报步长下0.25°ECMWF地面和高空预报数据

### 0.25°ECMWF地面数据

In [14]:
client = Client(source='ecmwf')

for step in np.arange(0,12,3):
    #通过.retrieve()方法获取想要的预报数据
    client.retrieve(
        date=start_time.strftime('%Y-%m-%d'),    #预测开始的日期
        time=start_time.strftime('%H'),          #预测开始的时间
        type='fc',          #预报数据
        stream='oper',
        param=['2t', 'sp'], #变量类型，这里选择了温度和气压
        step=str(step),           #预测步长，如果当前起报时为2024年02月21号00点，那么通过该方法会返回15点的数据
        target='ecmwf_2d_{}_fc_{}_0p25.grib2'.format(start_time.strftime('%Y%m%d%H'),str(step)),#存储名称
        resol='0p25',
        )

20240221180000-0h-scda-fc.grib2:   0%|          | 0.00/1.15M [00:00<?, ?B/s]

20240221180000-3h-scda-fc.grib2:   0%|          | 0.00/1.15M [00:00<?, ?B/s]

20240221180000-6h-scda-fc.grib2:   0%|          | 0.00/1.15M [00:00<?, ?B/s]

20240221180000-9h-scda-fc.grib2:   0%|          | 0.00/1.15M [00:00<?, ?B/s]

### 0.25°ECMWF高空数据

In [16]:
client = Client(source='ecmwf')
for step in np.arange(0,12,3):
    #通过.retrieve()方法获取想要的预报数据
    client.retrieve(
        date=start_time.strftime('%Y-%m-%d'),    #预测开始的日期
        time=start_time.strftime('%H'),          #预测开始的时间
        type='fc',          #预报数据
        stream='oper',
        param=['u', 'v'],  #变量类型，这里选择了温度和气压
        levelist=['850','500','200'], 
        step=str(step),           #预测步长，如果当前起报时为2024年02月21号00点，那么通过该方法会返回15点的数据
        target='ecmwf_3d_{}_fc_{}_0p25.grib2'.format(start_time.strftime('%Y%m%d%H'),str(step)), #存储名称
        resol='0p25',
        )

20240221180000-0h-scda-fc.grib2:   0%|          | 0.00/4.15M [00:00<?, ?B/s]

20240221180000-3h-scda-fc.grib2:   0%|          | 0.00/4.14M [00:00<?, ?B/s]

20240221180000-6h-scda-fc.grib2:   0%|          | 0.00/4.14M [00:00<?, ?B/s]

20240221180000-9h-scda-fc.grib2:   0%|          | 0.00/4.25M [00:00<?, ?B/s]

## grib格式转nc格式

In [17]:
def grib2nc(filename):

    ncname = filename.replace('.grib2','.nc')
    da = nc.Dataset(ncname,'w',format='NETCDF4')
    
    grb = pg.open(filename)
    g = grb[1]
    lat, lon = g.latlons()
    da.createDimension('lat', np.size(lat,0))
    da.createDimension('lon', np.size(lat,1))
    
    # add lat and lon variables
    da.createVariable('lat','f4',('lat','lon'),zlib=True,complevel=9,fill_value=-9999)
    da.createVariable('lon','f4',('lat','lon'),zlib=True,complevel=9,fill_value=-9999)
    da.variables['lat'][:]=lat
    da.variables['lon'][:]=lon
    
    for g in grb:
    
        # extract data and attribute
        varname = g.name
        data = g.values
        unit = g.units
        level = g.level

        
        # write into nc file
        if varname=='unknown':
            continue
        if level!=0 and level!=2 and level!=10:
            varname = varname + ' ' + str(level) + 'hPa'
        
        # print(varname)
        d = da.createVariable(varname,'f4',('lat','lon'),zlib=True,complevel=9,fill_value=-9999)
        d.units = unit
        da.variables[varname][:] = data
    
    da.close()
    grb.close()

In [20]:
filelist = glob('ecmwf_2d_*.grib2')
for file in tqdm(filelist):
    grib2nc(file)

100%|██████████| 8/8 [00:08<00:00,  1.05s/it]


In [21]:
filelist = glob('ecmwf_3d_*.grib2')
for file in tqdm(filelist):
    grib2nc(file)

100%|██████████| 8/8 [01:03<00:00,  7.94s/it]


In [4]:
!ls

data.grib2			     ecmwf_3d_2024022118_fc_0_0p25.grib2
ecmwf_2d_2024022118_fc_0_0p25.grib2  ecmwf_3d_2024022118_fc_0_0p25.nc
ecmwf_2d_2024022118_fc_0_0p25.nc     ecmwf_3d_2024022118_fc_0_0p4.grib2
ecmwf_2d_2024022118_fc_0_0p4.grib2   ecmwf_3d_2024022118_fc_0_0p4.nc
ecmwf_2d_2024022118_fc_0_0p4.nc      ecmwf_3d_2024022118_fc_3_0p25.grib2
ecmwf_2d_2024022118_fc_3_0p25.grib2  ecmwf_3d_2024022118_fc_3_0p25.nc
ecmwf_2d_2024022118_fc_3_0p25.nc     ecmwf_3d_2024022118_fc_3_0p4.grib2
ecmwf_2d_2024022118_fc_3_0p4.grib2   ecmwf_3d_2024022118_fc_3_0p4.nc
ecmwf_2d_2024022118_fc_3_0p4.nc      ecmwf_3d_2024022118_fc_6_0p25.grib2
ecmwf_2d_2024022118_fc_6_0p25.grib2  ecmwf_3d_2024022118_fc_6_0p25.nc
ecmwf_2d_2024022118_fc_6_0p25.nc     ecmwf_3d_2024022118_fc_6_0p4.grib2
ecmwf_2d_2024022118_fc_6_0p4.grib2   ecmwf_3d_2024022118_fc_6_0p4.nc
ecmwf_2d_2024022118_fc_6_0p4.nc      ecmwf_3d_2024022118_fc_9_0p25.grib2
ecmwf_2d_2024022118_fc_9_0p25.grib2  ecmwf_3d_2024022118_fc_9_0p25.nc
ecmwf_2d_2024022118_fc_9

## 用xarray模块读取与可视化

由于Coordinate中经纬度为二维数组，需要将`xarray`模块升级到较新版本才能读取

In [25]:
pip install xarray==2024.2 --user

  Using cached xarray-2024.2.0-py3-none-any.whl (1.1 MB)
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
geowombat 1.2.0 requires monotonic>=1.5, which is not installed.
geowombat 1.2.0 requires oset>=0.1.3, which is not installed.
geowombat 1.2.0 requires wget>=3.2, which is not installed.
Note: you may need to restart the kernel to use updated packages.


In [1]:
import xarray as xr
ds = xr.open_dataset('ecmwf_2d_2024022118_fc_0_0p25.nc')
ds

/home/mw/.local/lib/python3.9/site-packages/xarray/backends/plugins.py:80: RuntimeWarning: Engine 'cfradial1' loading failed:
cannot import name 'ParasiteAxesAuxTrans' from 'mpl_toolkits.axisartist' (/opt/conda/lib/python3.9/site-packages/mpl_toolkits/axisartist/__init__.py)
  warnings.warn(f"Engine {name!r} loading failed:\n{ex}", RuntimeWarning)


<xarray.Dataset> Size: 17MB
Dimensions:              (lat: 721, lon: 1440)
Coordinates:
    lat                  (lat, lon) float32 4MB ...
    lon                  (lat, lon) float32 4MB ...
Data variables:
    Surface pressure     (lat, lon) float32 4MB ...
    2 metre temperature  (lat, lon) float32 4MB ...


![Image Name](https://cdn.kesci.com/upload/s98soppflh.png)  
